# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Objectivists
email: steelwagstaff@gmail.com
description: > 
  A public website dedicated to the "Objectivist" poets: Louis Zukofsky, William Carlos Williams, George Oppen, Charles Reznikoff, Carl Rakosi, Basil Bunting, and Lorine Niedecker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SteelWagstaff
github_username:  SteelWagstaff

# Build settings
sass:
    sass_dir: _sass
include: ['_pages']
kramdown:
    input: GFM
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
